"""Block Service service layer for the DigitalThread API."""

from app.services_legacy import (
    create_block,
    update_block,
    create_block_draft_version,
    submit_block_for_review,
    approve_block,
    reject_block,
    send_block_back_to_draft,
    list_blocks,
    get_block_detail,
    list_block_history,
    create_block_containment,
    delete_block_containment,
    list_block_containments,
    create_sysml_relation,
    delete_sysml_relation,
    list_sysml_relations,
    build_block_tree,
    build_satisfaction_view,
    build_verification_view,
    build_derivation_view,
)

__all__ = [
    "create_block",
    "update_block",
    "create_block_draft_version",
    "submit_block_for_review",
    "approve_block",
    "reject_block",
    "send_block_back_to_draft",
    "list_blocks",
    "get_block_detail",
    "list_block_history",
    "create_block_containment",
    "delete_block_containment",
    "list_block_containments",
    "create_sysml_relation",
    "delete_sysml_relation",
    "list_sysml_relations",
    "build_block_tree",
    "build_satisfaction_view",
    "build_verification_view",
    "build_derivation_view",
]
