"""Federation Service service layer for the DigitalThread API."""

from app.services_legacy import (
    list_connectors,
    create_connector,
    update_connector,
    get_connector_service,
    list_external_artifact_versions,
    create_external_artifact_version,
    list_external_artifacts,
    create_external_artifact,
    update_external_artifact,
    get_external_artifact_service,
    list_artifact_links,
    create_artifact_link,
    delete_artifact_link,
    _validate_external_artifact,
    _validate_external_artifact_version,
    _resolve_external_artifact_version_for_project,
    _artifact_read,
    _resolve_artifact_link_internal_label,
    _resolve_artifact_link_external_label,
)

__all__ = [
    "list_connectors",
    "create_connector",
    "update_connector",
    "get_connector_service",
    "list_external_artifact_versions",
    "create_external_artifact_version",
    "list_external_artifacts",
    "create_external_artifact",
    "update_external_artifact",
    "get_external_artifact_service",
    "list_artifact_links",
    "create_artifact_link",
    "delete_artifact_link",
    "_validate_external_artifact",
    "_validate_external_artifact_version",
    "_resolve_external_artifact_version_for_project",
    "_artifact_read",
    "_resolve_artifact_link_internal_label",
    "_resolve_artifact_link_external_label",
]
